# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-19 14:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0003_movie_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='is_watched',
            field=models.BooleanField(default=True),
        ),
    ]
