# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-19 15:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0004_movie_is_watched'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='is_watched',
            field=models.BooleanField(default=False),
        ),
    ]
